# Generated by Django 3.2.8 on 2021-10-21 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups/')),
                ('intro_video', models.TextField(blank=True, null=True)),
                ('groupt_type', models.CharField(choices=[('Video', 'Video'), ('Audio', 'Audio'), ('Book', 'Book')], default='Video', max_length=32)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialgroup', to='club.status')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='videos/')),
                ('description', models.TextField(blank=True, null=True)),
                ('video_ru', models.TextField()),
                ('video_tm', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='club.materialgroup')),
            ],
        ),
        migrations.CreateModel(
            name='PDFMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='pdf/')),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_ru', models.TextField()),
                ('audio_tm', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfmaterial', to='club.materialgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='audio/')),
                ('description', models.TextField(blank=True, null=True)),
                ('audio_ru', models.TextField()),
                ('audio_tm', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_ru', models.TextField(blank=True, null=True)),
                ('pdf_tm', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='club.materialgroup')),
            ],
        ),
    ]
