# Generated by Django 3.2.8 on 2021-10-21 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_audio_materialgroup_pdfmaterial_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='pdfmaterial',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
