# Generated by Django 3.2.8 on 2021-10-21 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_auto_20211021_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdfmaterial',
            old_name='audio_ru',
            new_name='pdf_ru',
        ),
        migrations.RenameField(
            model_name='pdfmaterial',
            old_name='audio_tm',
            new_name='pdf_tm',
        ),
    ]
