# Generated by Django 3.2.8 on 2021-10-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20211021_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialgroup',
            old_name='groupt_type',
            new_name='group_type',
        ),
    ]
