# Generated by Django 3.2.8 on 2021-10-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_rename_groupt_type_materialgroup_group_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialgroup',
            name='group_type',
            field=models.CharField(choices=[('video', 'video'), ('audio', 'audio'), ('book', 'book')], default='video', max_length=32),
        ),
    ]
